#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT36XXX_HOSTDL_SPI) += nt36xxx.o nt36xxx_ext_proc.o
obj-$(CONFIG_TOUCHSCREEN_NT36XXX_FW_UPDATE) += nt36xxx_fw_update.o