--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -436,3 +436,4 @@ obj-$(CONFIG_INTELLI_PLUG) += intelli_plug.o
 obj-$(CONFIG_WALL_CLK) += wallclk.o
 obj-$(CONFIG_WALL_CLK_SYSFS) += wallclk_sysfs.o
 obj-$(CONFIG_MSM_CPUFREQ_LIMITER) += cpufreq_limit.o
+obj-$(CONFIG_FORCE_FAST_CHARGE) += fastchg.o
